name: Rolling restart
on: 
  workflow_dispatch: 
    inputs:
      customer_short_name:
        description: customer short name
        required: true
      environment:
        description: environment
        type: choice
        options:
          - dev
          - pord
      region:
        description: region
        type: choice
        options:
          - primary
          - secondary
jobs:
  restart-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "Restarting customer: ${{ github.event.inputs.customer_short_name }}"
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Region: ${{ github.event.inputs.region }}"

  
         
         
    
