name: Unlock Admin
on:
  workflow_dispatch:
jobs:
  second-job:
     runs-on: ubuntu-latest
     steps:
       - name: Print welcome message 
         run: echo "Welcome Unlock Admin"


       
      
  
